### ISSUE TITLE
There is no way to get a client id from app.musicapi.com

### ISSUE THREAD

**Issue by x-aether-x** [Fustigate8933/UtaYaku#2]
Could you please fix this or make the installation a bit more comprehensive?

**Comment by Fustigate8933** [comment]
Thank you for pointing that out! I will update the README soon.

**Comment by Fustigate8933** [comment]
I have updated the readme, let me know if it works for you, then I'll close the issue

**Comment by x-aether-x** [comment]
It works, thanks!
